<!DOCTYPE html>
<html lang="en">

<head>
  <?php // The header includes the head tag and start of body
  require "includes/head.php";
  ?>
  <meta property="og:title" content="<?php echo $META['shortName']; ?> Policy on use of AI tools" />
  <meta name="twitter:title" content="<?php echo $META['shortName']; ?> Policy on use of AI tools" />

  <title>
    <?php echo $META['shortName']; ?> AI Tool Policy
  </title>
</head>

<body>
  <?php require "includes/nav.php"; ?>

  <main class="container">
    <h2 class="indPageTitle">
      AI Tool Policy
    </h2>

    <p>
      We plan to generally follow the <a target="_blank" href="https://www.acm.org/publications/policies/frequently-asked-questions">ACM Policy on the use of AI tools</a>.
    </p>
    <p>
      If you have used generative AI for grammar, spell checking, and/or basic editing,
      please so state in the acknowledgement section. If you have used AI for more
      extensive editing, please disclose and describe all your AI-related
      edits, if not in the text, then in a supplementary material or
      appendix This description must include the AI version, prompt, query, etc, to the
      best of your ability.
    </p>

    <h3 class="pageSubtitle mt-4">
      FAQ
    </h3>

    <p>
      What follows is a paraphrased version of the ACM policy on AI tools.
    </p>

    <h4 class="subSubtitle">
      1) Can I use generative AI software tools to prepare my manuscript?
    </h4>
    <p>
      The use of such tools is permitted, subject to the following
      requirements:
    </p>
    <ol type="a">
      <li>
        That these systems do not plagiarize, misrepresent, or falsify content
        in the submissions.
      </li>
      <li>
        That the resulting Work in its totality is an accurate representation
        of the authors' underlying work and novel intellectual contributions and
        is not primarily the result of the tool's generative capabilities.
      </li>
      <li>
        That the authors accept responsibility for the veracity and
        correctness of all material in their Work, including any
        computer-generated material.
      </li>
    </ol>

    <h4 class="subSubtitle">
      2) If I use generative AI software tools, under what conditions must I
      disclose their use in my Work?
    </h4>
    <p>
      Today's generative AI software tools perform different tasks and it is
      reasonable to expect that their use and use cases will expand and become
      more robust over time.
      Whether disclosure in your published ACM Work is necessary depends on
      how you utilize these tools. The following guidelines should be followed
      when determining whether and to what extent disclosure must be provided
      in your Work.
    </p>
    <p>
      <em>If you are using generative AI software tools such as ChatGPT, Jasper,
        AI-Writer, Lex, or other similar tools to generate new content such as
        text, images, tables, code, etc.</em> you must disclose their use in either
      the acknowledgements section of the Work or elsewhere in the Work
      prominently. The level of disclosure should be commensurate with the
      proportion of new text or content generated by these tools.
    </p>
    <p>
      <em>If entire sections of a Work, including tables, graphs, images, and
        other content were generated by one of these tools</em>, you should disclose
      which sections and which tools and tool versions you used to generate
      those sections by preparing an Appendix or a Supplementary Material
      document that describes the use, including but not limited to the
      specific tools and versions, the text of the prompts provided as input,
      and any post-generation editing (such as rephrasing the generated text).
      Authors should also note that the amount or type of generated text
      allowable may vary depending on the type of the section or paper
      affected. For example, using such tools to generate portions of a
      Related Work section is fundamentally different than generating novel
      results or interpretations.
    </p>
    <p>
      <em>If the amount of text being generated is small (limited to phrases or
        sentences)</em>, then it would be sufficient to add a footnote to the
      relevant section of the submission utilizing the system(s) and include a
      general disclaimer in the Acknowledgements section.
    </p>
    <p>
      <em>If you are using generative AI software tools to edit and improve the
        quality of your existing text in much the same way you would use a
        typing assistant</em> like Grammarly to improve spelling, grammar,
      punctuation, clarity, engagement or to use a basic word processing
      system to correct spelling or grammar, it is not necessary to disclose
      such usage of these tools in your Work.
    </p>

    <h4 class="subSubtitle">
      3) Can a generative AI tool be listed as an author?
    </h4>
    <p>
      No!
    </p>
  </main>

  <?php include "includes/footer.php"; ?>

  <!-- Handlebars -->
  <script src="https://iacr.org/libs/js/handlebars/handlebars-v4.1.0.js" type="text/javascript"></script>
  <!-- Personal scripts -->
  <script src="js/committee.js"></script>

</body>

</html>